spring.application.name=ticket-service

server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5433/ticket_db
spring.datasource.username=ticket_user
spring.datasource.password=ticket_password
spring.jpa.hibernate.ddl-auto=update
employee.service.url=http://localhost:8081/api/employees

# Actuator Health Check & Monitoring
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always