version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ticket_system_db
    environment:
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data: