spring.application.name=employee-service

server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/employee_db
spring.datasource.username=ticket_user
spring.datasource.password=ticket_password
spring.jpa.hibernate.ddl-auto=update

# Actuator Health Check & Monitoring
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always